typography_spectrum: 0.5762227952945977
color:
  brandStrength: 0.32554429210722446
  lightness: 0.48256098246201873
  saturation: 0.6320053646340966
  rhythmicContrast: 0.1609831436071545
  brandColors:
    - '#DDDCC5'
    - '#958976'
    - '#611427'
    - '#1D2326'
    - '#6A6A61'
layout_spectrum: 0.4408460413105786
author:
  name: Gary A Guth
  email: gary@guth.us
  url: 'https://www.bagpipelessons.net'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9943dce3-599d-47fb-adfa-05b51492f578.jpg
name: BagpipeLessons.Net
title: Learn to play the bagpipe!
description: Our job is to "teach you how to practice this week".
